CLASS zeje_bloqi_class DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zeje_bloqi_class IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.

   out->write( 'ESTA ES MI PRIMERA CLASS' ).

  ENDMETHOD.

ENDCLASS.
